<?php

/* 
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/*   function tweet_preprocess_block(&$variables){
     dpm($variables);
}*/
/* attach jquery or any other library
function matt_page_alter(&$page) {
  $page['#attached']['library'][] = 'core/jquery';
} */
